#!/bin/bash
git config --global user.email canjiang.lu.x@gmail.com
git config --global user.name "Canjiang Lu"
git config --global format.signoff true
git config --global credential.helper store
git config --global push.default simple
git config --global http.sslverify false
git config --global http.proxy http://127.0.0.1:43943
git config --global https.proxy https://127.0.0.1:43943

#for kernel development only
git config --global core.abbrev 12
git config --global pretty.fixes 'Fixes: %h ("%s")'
#git log -1 --pretty=fixes HEAD

#git clone ssh://lcj@127.0.0.1:2222/xxx
#git config --global http.followRedirects true

#git remote add wq https://git.kernel.org/pub/scm/linux/kernel/git/tj/wq.git
#git fetch wq
#git branch --set-upstream-to wq/master


#https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
